name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: make binary

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: cmd/dcgm-exporter/dcgm-exporter.*
