name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: make binary

    - name: Lint
      run: make check-format

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: cmd/dcgm-exporter/dcgm-exporter.*
